# Generated by Django 5.0.4 on 2024-04-27 17:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='code',
            field=models.CharField(max_length=256, unique=True, verbose_name='Kategoriya kodi'),
        ),
        migrations.CreateModel(
            name='CategoryRawMaterialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_of_measure1', models.CharField(choices=[('dona', 'Soni'), ('m', 'Metr'), ('m2', 'Metr kvadrat')], max_length=256, verbose_name="O'lchov birligi")),
                ('quantity1', models.FloatField(verbose_name='Qancha?')),
                ('unit_of_measure2', models.CharField(choices=[('dona', 'Soni'), ('m', 'Metr'), ('m2', 'Metr kvadrat')], max_length=256, verbose_name="O'lchov birligi")),
                ('quantity2', models.FloatField(verbose_name='Qancha?')),
                ('unit_of_measure3', models.CharField(choices=[('dona', 'Soni'), ('m', 'Metr'), ('m2', 'Metr kvadrat')], max_length=256, verbose_name="O'lchov birligi")),
                ('quantity3', models.FloatField(verbose_name='Qancha?')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='werehouse.categorymodel')),
                ('raw_material_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_id1', to='werehouse.rawmaterialmodel')),
                ('raw_material_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_id2', to='werehouse.rawmaterialmodel')),
                ('raw_material_id3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_id3', to='werehouse.rawmaterialmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
