# Generated by Django 5.0.4 on 2024-04-27 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werehouse', '0002_alter_categorymodel_code_categoryrawmaterialmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryrawmaterialmodel',
            name='raw_material_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_id1', to='werehouse.rawmaterialmodel', verbose_name='Qaysi xomashyo?'),
        ),
        migrations.AlterField(
            model_name='categoryrawmaterialmodel',
            name='raw_material_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_id2', to='werehouse.rawmaterialmodel', verbose_name='Qaysi xomashyo?'),
        ),
        migrations.AlterField(
            model_name='categoryrawmaterialmodel',
            name='raw_material_id3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_material_id3', to='werehouse.rawmaterialmodel', verbose_name='Qaysi xomashyo?'),
        ),
    ]
